name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  check-train-workflow-status:
    runs-on: ubuntu-latest
    outputs:
      train_workflow_success: ${{ steps.check-train-workflow-success.outputs.train_workflow_success }}
    steps:
      - name: Check status of Train Workflow
        id: check-train-workflow-success
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const prNumber = context.payload.pull_request.number;
            const repo = context.repo;
            let workflowSuccess = false;
            
            // Get all workflow runs for "Train" workflow
            const runs = await github.rest.actions.listWorkflowRuns({
              ...repo,
              workflow_id: 'train.yml',
              branch: 'main'
            });
            console.log(`Checking workflow runs for PR #${prNumber}`);
            for (const run of runs.data.workflow_runs) {
              console.log(`Run ${run.id}: Conclusion=${run.conclusion}, Associated PRs=${run.pull_requests.map(pr => pr.number).join(', ')}`);
            }
            // Find a run associated with the current PR and check its conclusion
            for (const run of runs.data.workflow_runs) {
              if (run.pull_requests.some(pr => pr.number === prNumber) && run.conclusion === 'success') {
                workflowSuccess = true;
                break;
              }
            }

            // Set output for the next job to use
            core.setOutput('train_workflow_success', workflowSuccess.toString());

  pull-and-run:
    needs: check-train-workflow-status
    if: ${{ needs.check-train-workflow-status.outputs.train_workflow_success == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker image
        run: docker pull harshajk/cicd_assignment:latest

      - name: Run Docker image and check score
        id: run_image
        run: |
          SCORE=$(docker run harshajk/cicd_assignment:latest | tail -n 1)
          echo "Score was $SCORE"
          if (( $(echo "$SCORE > 0.50" | bc -l) )); then
            echo "Score is greater than 0.50, success!"
          else
            echo "Score is not greater than 0.50, failing the job."
            exit 1
